# Generated by Django 3.0.6 on 2020-06-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingsres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='sub_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kingsres.FoodSubCategory'),
        ),
    ]
