# Generated by Django 3.0.6 on 2020-06-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingsres', '0002_auto_20200612_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='kingsres.FoodSubCategory'),
            preserve_default=False,
        ),
    ]
