# Generated by Django 3.0.6 on 2020-06-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingsres', '0003_foodcategory_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='foodsubcategory',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='kingsres.FoodCategory'),
            preserve_default=False,
        ),
    ]
