# Generated by Django 3.0.6 on 2020-06-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingsres', '0004_auto_20200614_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
